controller_list:
  - name: fake_panda_arm_controller
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_hand_controller
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
  - name: fake_panda_1_arm_controller
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_1_hand_controller
    joints:
      - panda_1_finger_joint1
      - panda_1_finger_joint2
  - name: fake_panda_2_arm_controller
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_2_hand_controller
    joints:
      - panda_2_finger_joint1
      - panda_2_finger_joint2
initial:
  - group: panda_arm
    pose: ready
  - group: panda_effector
    pose: open
  - group: panda_1_arm
    pose: ready
  - group: panda_1_effector
    pose: open
  - group: panda_2_arm
    pose: ready
  - group: panda_2_effector
    pose: open
